name: rd_example
description: A sample command-line application
#dependencies:
#  unittest: any

name: rd_example
version: 0.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: An example how to use rd (random data), a library for educational purposes.
homepage: http://ondart.me/
dependencies:
  rd:
    git: git://github.com/dzenanr/rd.git
